### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by luhugerth** [nlapier2/Metalign#18]
Due to constrians described in the docker issue, I'm running Metalign in an interactive Docker session. It seems to work ok, but I get the following error:

`python /home/Metalign/metalign.py --output $output --length_normalize --no_quantify_unmapped         --read_cutoff $threshold $inter $DATA `

> [M::main] Real time: 2859.096 sec; CPU: 6444.166 sec; Peak RSS: 23.846 GB
> Traceback (most recent call last):
>   File "/home/Metalign/map_and_profile.py", line 545, in <module>
>     map_main(args)
>   File "/home/Metalign/map_and_profile.py", line 539, in map_main
>     rank_results = gather_results(args, acc2info, taxid2info)
>   File "/home/Metalign/map_and_profile.py", line 456, in gather_results
>     file_res = compute_abundances(args, infile, acc2info, taxid2info)
>   File "/home/Metalign/map_and_profile.py", line 446, in compute_abundances
>     results = tree_results_cami(args, taxids2abs)
>   File "/home/Metalign/map_and_profile.py", line 389, in tree_results_cami
>     taxids2abs = rank_renormalize(args, taxids2abs, only_strains=True)
>   File "/home/Metalign/map_and_profile.py", line 352, in rank_renormalize
>     clades2abs[clade][-1]/= (rank_totals[clades2abs[clade][1]] / mapped_pct)
> ZeroDivisionError: float division by zero

I get the same error if I try running the two steps separately:
`python /home/Metalign/select_db.py --strain_level --db ${inter%fq}fna $inter $DATA`
`python /home/Metalign/map_and_profile.py --length_normalize --no_quantify_unmapped --db ${inter%fq}fna $inter $DATA`

**Comment by nlapier2** [comment]
This error happens when no reads have been mapped successfully. I will add an update to the software to catch this error and print a more intuitive message.

As for why no reads are being mapped, it would be helpful for me to see a couple reads from the file and the output from the KMC and CMash steps.

**Comment by dkoslicki** [comment]
@luhugerth it may be helpful to run `metalign.py` with the option `--temp_dir <temp_dir>` and to send the first few lines (if any) of the file `60mers_intersection_dump.fa` as this is what gets handed off to CMash.

**Comment by luhugerth** [comment]
Update: it ran without problems removing the `--no_quantify_unmapped` flag, giving 97.5% mapping to Bacteria.

**Comment by nlapier2** [comment]
> Update: it ran without problems removing the `--no_quantify_unmapped` flag, giving 97.5% mapping to Bacteria.

That's very interesting. I'll have to look into why this issue may be cropping up for that setting.
