### ISSUE TITLE
Metalign run error

### ISSUE THREAD

**Issue by premkrishnan** [nlapier2/Metalign#40]
Hi,

I am new to this and just starting to try out Metalign. Appreciate your help to figure out the following issue that I am facing.

First, I tested with sample data file.

**TESTING**: Installed Metalign as mentioned in Wiki page and successfully ran with the example file (wget https://ucla.box.com/shared/static/ybz1xgke32kh56p4lqsg41t4g1bq8xy0.gz && mv ybz1xgke32kh56p4lqsg41t4g1bq8xy0.gz reads.fna.gz). 
**I managed to generate the output file successfully.**

Then I decided to replicate the analysis as mentioned in the Metalign publication.
1. Downloaded study sample from EBI (https://www.ebi.ac.uk/ena/data/view/PRJEB1787). Accession: ERR598952(both R1 & R2)
2. Created "interleaved" FASTQ (input file) file using BBMap/reformat.sh
3. Run Metalign
_(It is a PBS script)_

#PBS -N metalign
#PBS -l select=1:ncpus=72
#PBS -q himem3
#PBS -j oe
#PBS -o logs-tara-test

cd $PBS_O_WORKDIR

#inputs
DATA=/cm/shared/apps/build/Metalign
IN=test.interleaved.fastq
OUT=test.interleave.tsv

#load module and run metalign
module load metalign/0.12.5
metalign.py $IN $DATA --output $OUT

#END

**A few errors popped up and I am not sure what they are**:

_Sample_:
Finished reading in/creating ternary search tree
Time: 3.368100
/gpfs1/scratch/prabu/anaconda3/envs/Metalign/lib/python3.8/site-packages/screed/openscreed.py:64: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if compression is 'bz2':
/gpfs1/scratch/prabu/anaconda3/envs/Metalign/lib/python3.8/site-packages/screed/openscreed.py:67: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif compression is 'gz':
Start streaming
Traceback (most recent call last):
  File "/gpfs1/scratch/prabu/anaconda3/envs/Metalign/bin/StreamingQueryDNADatabase.py", line 183, in <module>
    fid = khmer.ReadParser(query_file)  # This is faster than screed
**OSError: File /cm/shared/apps/build/Metalign/frap8xqi/60mers_intersection_dump.fa does not contain any sequences!**
Traceback (most recent call last):
  File "/gpfs1/scratch/prabu/anaconda3/envs/Metalign/bin/metalign.py", line 91, in <module>
    main()
  File "/gpfs1/scratch/prabu/anaconda3/envs/Metalign/bin/metalign.py", line 84, in main
    select.select_main(args)  # runs select_db routine
  File "/gpfs1/scratch/prabu/anaconda3/envs/Metalign/bin/select_db.py", line 158, in select_main
    organisms_to_include = run_cmash_and_cutoff(args, taxid2info)
  File "/gpfs1/scratch/prabu/anaconda3/envs/Metalign/bin/select_db.py", line 81, in run_cmash_and_cutoff
    with(open(cmash_out, 'r')) as cmash_results:
**FileNotFoundError: [Errno 2] No such file or directory: '/cm/shared/apps/build/Metalign/frap8xqi/cmash_query_results.csv'**

**Full LOG FILE is attached herewith.**
[logs-tara-test.txt](https://github.com/nlapier2/Metalign/files/7127382/logs-tara-test.txt)

Can anyone help me find out the issue. Please let me know if you require clarification.

Thanks in advance.

-Prem

**Comment by nlapier2** [comment]
Hi Prem, 

Sorry for the late reply -- I was on vacation when this was posted. Based on the first error, it seems that you have an old version of screed, as screed has now changed "compression is 'bz2'" to "compression == 'bz2'" -- you can verify this via their repo if you'd like. I am not entirely sure if this is because the CMash conda build specifies a certain version of screed, or if you just have to try updating screed yourself. Did you install Metalign via conda, or manually? It may be difficult to get all the dependency versions right if you do the manual install. Otherwise, I am not really sure -- I haven't encountered this issue.

Best,
Nathan

**Comment by premkrishnan** [comment]
> Hi Prem,
> 
> Sorry for the late reply -- ...........
> 
> Best, Nathan

Hi Nathan,
Thanks for replying :) 
I installed through conda, not manually. I will try to update screed and see what happens. I will keep you posted.

-Prem

**Comment by luizirber** [comment]
I think the issue is that the instruction to install Metalign in https://github.com/nlapier2/Metalign/wiki#bioconda-version :
`conda install -c bioconda Metalign`
is underspecified. If you want a one-line install, then it needs to include `conda-forge` too:
`conda install -c conda-forge -c bioconda Metalign`
but the better approach is to follow the bioconda setup instructions in http://bioconda.github.io/user/install.html#set-up-channels and run
```
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
```

(incidentally, `screed` was moved to conda-forge, so this is probably a fairly old version being installed)

**Comment by luizirber** [comment]
That said, I think the error is that `/cm/shared/apps/build/Metalign/frap8xqi/60mers_intersection_dump.fa` seems to be empty? screed is not even being used (there are `SyntaxWarning`s, but they are not fatal), it is actually `khmer.ReadParser` that is reading the file and throwing the fatal error.

**Comment by nlapier2** [comment]
Thanks Luiz, I have updated that line in the wiki. I did notice that screed is only throwing warnings, but I wondered if this could indicate downstream problems, e.g. if the compressed file is not being read properly then there would be no k-mer intersection. Perhaps not, but then I'm not really sure what the problem is...
