### ISSUE TITLE
Missing Files?

### ISSUE THREAD

**Issue by echolley31** [nlapier2/Metalign#44]
I've been trying to get metalign up and running for a metagenomics project I'm working on. I originally realized when I cloned the github repository, the db_info.txt file was not present and was giving me an error. I then googled for the file and found it published by you online. When I got that downloaded it ran for a bit, and then gave me the following message:

(metalign) 53 [vortex] metalign.py reads.fna /sciclone/scr10/echolley/igem/Metalign/data
******

********** Used parameters for Stage 1 : **********
No. of input files  : 1
Output file name  :
No. of working directories  : 1
Input format  : FASTA
Output format : KMC

k-mer length  : 60
Max. k-mer length : 256
Signature length  : 9
Both strands  : true
RAM only mode : false

******* Stage 1 configuration: *******

No. of bins : 512
Bin part size : 65536
Input buffer size : 16777216

No. of readers  : 1
No. of splitters  : 3

Max. mem. size  : 12000MB
Max. mem. per storer  : 6177MB
Max. mem. for single package : 24MB

Max. mem. for PMM (bin parts): 9504MB
Max. mem. for PMM (FASTQ) : 1684MB
Max. mem. for PMM (reads) :  3MB
Max. mem. for PMM (b. reader):  805MB

Stage 1: 100%

********** Used parameters for Stage 2 : **********
Min. count threshold  : 2
Max. count threshold  : 1000000000
Max. counter value  : 3

******* Stage 2 configuration: *******
No. of threads  : 4

Max. mem. for 2nd stage :  775MB

Stage 2: 100%
1st stage: 1.71258s
2nd stage: 4.20068s
Total : 5.91326s
Tmp size : 44MB

Stats:
No. of k-mers below min. threshold :  23198756
No. of k-mers above max. threshold : 0
No. of unique k-mers  :  33795549
No. of unique counted k-mers  :  10596793
Total no. of k-mers :  49395545
Total no. of reads  :  300969
Total no. of super-k-mers : 2022470
Error: Cannot open file /sciclone/scr10/echolley/igem/Metalign/data/cmash_db_n1000_k60_dump.kmc_pre
KMC dump ver. 3.2.4 (2024-02-09)

Usage:
kmc_dump [options] <kmc_database> <output_file>
Parameters:
<kmc_database> - kmer_counter's output
Options:
-ci<value> - exclude k-mers occurring less than <value> times
-cx<value> - exclude k-mers occurring more of than <value> times
Traceback (most recent call last):
File "/sciclone/home/echolley/.conda/envs/metalign/bin/StreamingQueryDNADatabase.py", line 117, in <module>
raise Exception("Training/reference file %s does not exist." % training_database_file)
Exception: Training/reference file /sciclone/scr10/echolley/igem/Metalign/data/cmash_db_n1000_k60.h5 does not exist.
Traceback (most recent call last):
File "/sciclone/home/echolley/.conda/envs/metalign/bin/metalign.py", line 91, in <module>
main()
File "/sciclone/home/echolley/.conda/envs/metalign/bin/metalign.py", line 84, in main
select.select_main(args) # runs select_db routine
File "/sciclone/home/echolley/.conda/envs/metalign/bin/select_db.py", line 158, in select_main
organisms_to_include = run_cmash_and_cutoff(args, taxid2info)
File "/sciclone/home/echolley/.conda/envs/metalign/bin/select_db.py", line 81, in run_cmash_and_cutoff
with(open(cmash_out, 'r')) as cmash_results:
FileNotFoundError: [Errno 2] No such file or directory: '/sciclone/scr10/echolley/igem/Metalign/data/9xykd9nm/cmash_query_results.csv'

I have looked in all of the folders in everything that was downloaded in the github clone, but I cannot find these. Any suggestions? Thank you!

**Comment by nlapier2** [comment]
Hello, thanks for your interest in Metalign! I haven't seen that before, but it seems to me like this could happen if either (1) the data wasn't all downloaded correctly or (2) you don't have write permission to the data/ folder. Could you check those? Did you run setup_data.sh in the scripts/ folder?

**Comment by darlenewagner** [comment]
The scripts/ and data/ folders are missing in my installation of my_conda_envs/metalign    
thanks,
